# Pandas

## Two building blocks: series and dataframe

### series

In [2]:
import pandas as pd

In [3]:
test_series = pd.Series([2,3,4,5,6,7,8], index = ["sunday", "mon", "tue", "wed", "thur", "fri", "sat"])
test_series

sunday    2
mon       3
tue       4
wed       5
thur      6
fri       7
sat       8
dtype: int64

In [4]:
type(test_series)

pandas.core.series.Series

In [5]:
test_series.index

Index(['sunday', 'mon', 'tue', 'wed', 'thur', 'fri', 'sat'], dtype='object')

In [6]:
test_series.index.tolist()

['sunday', 'mon', 'tue', 'wed', 'thur', 'fri', 'sat']

### DataFrame

In [8]:
# Create a dataframe from a dictionary: having keys {'name':[], 'score':[]}
score = pd.DataFrame({"name":["Hari","Basanta","Gopi"],
              "score":[22,34,45]})

score

      name  score
0     Hari     22
1  Basanta     34
2     Gopi     45

In [9]:
type(score)

pandas.core.frame.DataFrame

In [11]:
score.index

RangeIndex(start=0, stop=3, step=1)

In [13]:
# create a dataframe from list of dictionaries

score = pd.DataFrame([{"name":"hari","score":22},
                      {"name":"basanta","score":34},
                      {"name":"gopi","score":45}])

score

      name  score
0     hari     22
1  basanta     34
2     gopi     45

## Loading csv and excel

In [21]:
df = pd.read_csv("class_scores.csv")
df.head()

,student_id,name,city,subject,marks,attendance_percent,exam_date
0,101,Aarav Sharma,Kathmandu,Python Programming,88,95.0,2026-05-02
1,102,Bibek Thapa,Pokhara,Statistics,72,88.5,2026-05-03
2,103,Chandni Rai,Biratnagar,Python Programming,45,70.0,2026-05-02
3,104,Deepika Gurung,Kathmandu,Machine Learning,91,98.0,2026-05-04
4,105,Esha KC,Lalitpur,Statistics,67,80.0,2026-05-03

In [22]:
df.tail()

,student_id,name,city,subject,marks,attendance_percent,exam_date
15,116,Prakash Yadav,Biratnagar,Machine Learning,77,89.0,2026-05-04
16,117,Queenie Rana,Pokhara,Python Programming,33,50.0,2026-05-02
17,118,Rohit Bista,Kathmandu,Statistics,85,92.0,2026-05-03
18,119,Sabina Ghale,Butwal,SQL,62,78.0,2026-05-05
19,120,Tenzin Sherpa,Lalitpur,Machine Learning,93,97.0,2026-05-04

In [23]:
df.shape

(20, 7)

### checking structure: info(), describe()

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   student_id          20 non-null     int64
 1   name                20 non-null     object
 2   city                20 non-null     object
 3   subject             20 non-null     object
 4   marks               20 non-null     int64
 5   attendance_percent  20 non-null     float64
 6   exam_date           20 non-null     object
dtypes: float64(1), int64(2), object(4)
memory usage: 1.2+ KB

In [25]:
df.describe()

       student_id      marks  attendance_percent
count    20.00000  20.000000           20.000000
mean    110.50000  69.150000           80.825000
std       5.91608  18.790465           14.886655
min     101.00000  33.000000           50.000000
25%     105.75000  57.250000           71.500000
50%     110.50000  70.000000           83.500000
75%     115.25000  85.750000           92.750000
max     120.00000  95.000000           99.000000

## Column selection

In [26]:
df["marks"]

0     88
1     72
2     45
3     91
4     67
5     58
6     39
7     82
8     95
9     61
10    74
11    48
12    90
13    55
14    68
15    77
16    33
17    85
18    62
19    93
Name: marks, dtype: int64

In [28]:
# multiple column
df_new = df[["marks","attendance_percent"]]

In [29]:
df_new

    marks  attendance_percent
0      88                95.0
1      72                88.5
2      45                70.0
3      91                98.0
4      67                80.0
5      58                65.0
6      39                55.0
7      82                90.0
8      95                99.0
9      61                72.0
10     74                85.0
11     48                60.0
12     90                96.0
13     55                75.0
14     68                82.0
15     77                89.0
16     33                50.0
17     85                92.0
18     62                78.0
19     93                97.0

## Selecting rows: loc and iloc

In [30]:
df.loc[2:5]

,student_id,name,city,subject,marks,attendance_percent,exam_date
2,103,Chandni Rai,Biratnagar,Python Programming,45,70.0,2026-05-02
3,104,Deepika Gurung,Kathmandu,Machine Learning,91,98.0,2026-05-04
4,105,Esha KC,Lalitpur,Statistics,67,80.0,2026-05-03
5,106,Faisal Khan,Butwal,Python Programming,58,65.0,2026-05-02

In [31]:
df.iloc[2:5]

,student_id,name,city,subject,marks,attendance_percent,exam_date
2,103,Chandni Rai,Biratnagar,Python Programming,45,70.0,2026-05-02
3,104,Deepika Gurung,Kathmandu,Machine Learning,91,98.0,2026-05-04
4,105,Esha KC,Lalitpur,Statistics,67,80.0,2026-05-03

### slicing rows and columns together

In [ ]:
# the end like [0,4] here 4 is inclusive in loc
df.loc[0:4,["name","subject","marks"]]

             name             subject  marks
0    Aarav Sharma  Python Programming     88
1     Bibek Thapa          Statistics     72
2     Chandni Rai  Python Programming     45
3  Deepika Gurung    Machine Learning     91
4         Esha KC          Statistics     67

In [ ]:
# 5 is exclusive in iloc
df.iloc[0:5,1:4]

             name        city             subject
0    Aarav Sharma   Kathmandu  Python Programming
1     Bibek Thapa     Pokhara          Statistics
2     Chandni Rai  Biratnagar  Python Programming
3  Deepika Gurung   Kathmandu    Machine Learning
4         Esha KC    Lalitpur          Statistics

In [35]:
# use .iloc() and select first 3 rows and columns: name,city
df.iloc[0:3,1:3]

           name        city
0  Aarav Sharma   Kathmandu
1   Bibek Thapa     Pokhara
2   Chandni Rai  Biratnagar

In [34]:
df

,student_id,name,city,subject,marks,attendance_percent,exam_date
0,101,Aarav Sharma,Kathmandu,Python Programming,88,95.0,2026-05-02
1,102,Bibek Thapa,Pokhara,Statistics,72,88.5,2026-05-03
2,103,Chandni Rai,Biratnagar,Python Programming,45,70.0,2026-05-02
3,104,Deepika Gurung,Kathmandu,Machine Learning,91,98.0,2026-05-04
4,105,Esha KC,Lalitpur,Statistics,67,80.0,2026-05-03
5,106,Faisal Khan,Butwal,Python Programming,58,65.0,2026-05-02
6,107,Gita Adhikari,Pokhara,Machine Learning,39,55.0,2026-05-04
7,108,Hari Bahadur,Kathmandu,SQL,82,90.0,2026-05-05
8,109,Isha Shrestha,Lalitpur,Statistics,95,99.0,2026-05-03
9,110,Jeevan Lama,Biratnagar,Python Programming,61,72.0,2026-05-02
10,111,Kabita Basnet,Kathmandu,SQL,74,85.0,2026-05-05
11,112,Lokesh Poudel,Pokhara,Machine Learning,48,60.0,2026-05-04
12,113,Maya Tamang,Butwal,Python Programming,90,96.0,2026-05-02
13,114,Nabin Karki,Kathmandu,Statistics,55,75.0,2026-05-03
14,115,Oshin Magar,Lalitpur,SQL,68,82.0,2026-05-05
15,116,Prakash Yadav,Biratnagar,Machine Learning,77,89.0,2026-05-04
16,117,Queenie Rana,Pokhara,Python Programming,33,50.0,2026-05-02
17,118,Rohit Bista,Kathmandu,Statistics,85,92.0,2026-05-03
18,119,Sabina Ghale,Butwal,SQL,62,78.0,2026-05-05
19,120,Tenzin Sherpa,Lalitpur,Machine Learning,93,97.0,2026-05-04

In [36]:
print(df.head(3).iloc[1:3])

   student_id         name        city             subject  marks  \
1         102  Bibek Thapa     Pokhara          Statistics     72
2         103  Chandni Rai  Biratnagar  Python Programming     45

   attendance_percent   exam_date
1                88.5  2026-05-03
2                70.0  2026-05-02

In [39]:
# implement using .loc method
df.loc[0:2,["name","city"]]

           name        city
0  Aarav Sharma   Kathmandu
1   Bibek Thapa     Pokhara
2   Chandni Rai  Biratnagar

In [40]:
df.loc[0:2, 'name':'city']

           name        city
0  Aarav Sharma   Kathmandu
1   Bibek Thapa     Pokhara
2   Chandni Rai  Biratnagar

## Boolean filtering

In [42]:
df["marks"] > 50

0      True
1      True
2     False
3      True
4      True
5      True
6     False
7      True
8      True
9      True
10     True
11    False
12     True
13     True
14     True
15     True
16    False
17     True
18     True
19     True
Name: marks, dtype: bool

In [43]:
df.head()

,student_id,name,city,subject,marks,attendance_percent,exam_date
0,101,Aarav Sharma,Kathmandu,Python Programming,88,95.0,2026-05-02
1,102,Bibek Thapa,Pokhara,Statistics,72,88.5,2026-05-03
2,103,Chandni Rai,Biratnagar,Python Programming,45,70.0,2026-05-02
3,104,Deepika Gurung,Kathmandu,Machine Learning,91,98.0,2026-05-04
4,105,Esha KC,Lalitpur,Statistics,67,80.0,2026-05-03

In [45]:
df[df["marks"]>50]

,student_id,name,city,subject,marks,attendance_percent,exam_date
0,101,Aarav Sharma,Kathmandu,Python Programming,88,95.0,2026-05-02
1,102,Bibek Thapa,Pokhara,Statistics,72,88.5,2026-05-03
3,104,Deepika Gurung,Kathmandu,Machine Learning,91,98.0,2026-05-04
4,105,Esha KC,Lalitpur,Statistics,67,80.0,2026-05-03
5,106,Faisal Khan,Butwal,Python Programming,58,65.0,2026-05-02
7,108,Hari Bahadur,Kathmandu,SQL,82,90.0,2026-05-05
8,109,Isha Shrestha,Lalitpur,Statistics,95,99.0,2026-05-03
9,110,Jeevan Lama,Biratnagar,Python Programming,61,72.0,2026-05-02
10,111,Kabita Basnet,Kathmandu,SQL,74,85.0,2026-05-05
12,113,Maya Tamang,Butwal,Python Programming,90,96.0,2026-05-02
13,114,Nabin Karki,Kathmandu,Statistics,55,75.0,2026-05-03
14,115,Oshin Magar,Lalitpur,SQL,68,82.0,2026-05-05
15,116,Prakash Yadav,Biratnagar,Machine Learning,77,89.0,2026-05-04
17,118,Rohit Bista,Kathmandu,Statistics,85,92.0,2026-05-03
18,119,Sabina Ghale,Butwal,SQL,62,78.0,2026-05-05
19,120,Tenzin Sherpa,Lalitpur,Machine Learning,93,97.0,2026-05-04

In [46]:
df[(df["marks"]>50) & (df["attendance_percent"] > 70)]

,student_id,name,city,subject,marks,attendance_percent,exam_date
0,101,Aarav Sharma,Kathmandu,Python Programming,88,95.0,2026-05-02
1,102,Bibek Thapa,Pokhara,Statistics,72,88.5,2026-05-03
3,104,Deepika Gurung,Kathmandu,Machine Learning,91,98.0,2026-05-04
4,105,Esha KC,Lalitpur,Statistics,67,80.0,2026-05-03
7,108,Hari Bahadur,Kathmandu,SQL,82,90.0,2026-05-05
8,109,Isha Shrestha,Lalitpur,Statistics,95,99.0,2026-05-03
9,110,Jeevan Lama,Biratnagar,Python Programming,61,72.0,2026-05-02
10,111,Kabita Basnet,Kathmandu,SQL,74,85.0,2026-05-05
12,113,Maya Tamang,Butwal,Python Programming,90,96.0,2026-05-02
13,114,Nabin Karki,Kathmandu,Statistics,55,75.0,2026-05-03
14,115,Oshin Magar,Lalitpur,SQL,68,82.0,2026-05-05
15,116,Prakash Yadav,Biratnagar,Machine Learning,77,89.0,2026-05-04
17,118,Rohit Bista,Kathmandu,Statistics,85,92.0,2026-05-03
18,119,Sabina Ghale,Butwal,SQL,62,78.0,2026-05-05
19,120,Tenzin Sherpa,Lalitpur,Machine Learning,93,97.0,2026-05-04

In [52]:
# filter students from kathmandu having subjects python programming or machine learning
df[(df["city"]=='Kathmandu') & ((df["subject"] == 'Python Programming') | (df["subject"] == 'Machine Learning'))]

,student_id,name,city,subject,marks,attendance_percent,exam_date
0,101,Aarav Sharma,Kathmandu,Python Programming,88,95.0,2026-05-02
3,104,Deepika Gurung,Kathmandu,Machine Learning,91,98.0,2026-05-04

## A more readable style: df.query()

In [57]:
df.query("city == 'Kathmandu' and (subject == 'Python Programming' or subject == 'Machine Learning')")

,student_id,name,city,subject,marks,attendance_percent,exam_date
0,101,Aarav Sharma,Kathmandu,Python Programming,88,95.0,2026-05-02
3,104,Deepika Gurung,Kathmandu,Machine Learning,91,98.0,2026-05-04

In [58]:
df.dtypes

student_id              int64
name                   object
city                   object
subject                object
marks                   int64
attendance_percent    float64
exam_date              object
dtype: object

In [59]:
df["passed"] = df["marks"] > 40

In [60]:
df

,student_id,name,city,subject,marks,attendance_percent,exam_date,passed
0,101,Aarav Sharma,Kathmandu,Python Programming,88,95.0,2026-05-02,True
1,102,Bibek Thapa,Pokhara,Statistics,72,88.5,2026-05-03,True
2,103,Chandni Rai,Biratnagar,Python Programming,45,70.0,2026-05-02,True
3,104,Deepika Gurung,Kathmandu,Machine Learning,91,98.0,2026-05-04,True
4,105,Esha KC,Lalitpur,Statistics,67,80.0,2026-05-03,True
5,106,Faisal Khan,Butwal,Python Programming,58,65.0,2026-05-02,True
6,107,Gita Adhikari,Pokhara,Machine Learning,39,55.0,2026-05-04,False
7,108,Hari Bahadur,Kathmandu,SQL,82,90.0,2026-05-05,True
8,109,Isha Shrestha,Lalitpur,Statistics,95,99.0,2026-05-03,True
9,110,Jeevan Lama,Biratnagar,Python Programming,61,72.0,2026-05-02,True
10,111,Kabita Basnet,Kathmandu,SQL,74,85.0,2026-05-05,True
11,112,Lokesh Poudel,Pokhara,Machine Learning,48,60.0,2026-05-04,True
12,113,Maya Tamang,Butwal,Python Programming,90,96.0,2026-05-02,True
13,114,Nabin Karki,Kathmandu,Statistics,55,75.0,2026-05-03,True
14,115,Oshin Magar,Lalitpur,SQL,68,82.0,2026-05-05,True
15,116,Prakash Yadav,Biratnagar,Machine Learning,77,89.0,2026-05-04,True
16,117,Queenie Rana,Pokhara,Python Programming,33,50.0,2026-05-02,False
17,118,Rohit Bista,Kathmandu,Statistics,85,92.0,2026-05-03,True
18,119,Sabina Ghale,Butwal,SQL,62,78.0,2026-05-05,True
19,120,Tenzin Sherpa,Lalitpur,Machine Learning,93,97.0,2026-05-04,True

## Cleanup

### Basic datatype conversion

In [61]:
df["marks"].dtype

dtype('int64')

In [63]:
df["marks"] = df["marks"].astype(float)

In [64]:
df["marks"].dtypes

dtype('float64')

### handling dates

In [65]:
df["exam_date"].dtypes

dtype('O')

In [66]:
df["exam_date"] = pd.to_datetime(df["exam_date"])

In [67]:
df["exam_date"].dtypes

dtype('<M8[ns]')

In [68]:
df["exam_date"].dt.day_name()

0     Saturday
1       Sunday
2     Saturday
3       Monday
4       Sunday
5     Saturday
6       Monday
7      Tuesday
8       Sunday
9     Saturday
10     Tuesday
11      Monday
12    Saturday
13      Sunday
14     Tuesday
15      Monday
16    Saturday
17      Sunday
18     Tuesday
19      Monday
Name: exam_date, dtype: object

In [71]:
df["exam_date"] > "2025-01-02"

0     True
1     True
2     True
3     True
4     True
5     True
6     True
7     True
8     True
9     True
10    True
11    True
12    True
13    True
14    True
15    True
16    True
17    True
18    True
19    True
Name: exam_date, dtype: bool