# Pandas

## Two building blocks: series and dataframe

### series

In [2]:
import pandas as pd

In [3]:
test_series = pd.Series([2,3,4,5,6,7,8], index = ["sunday", "mon", "tue", "wed", "thur", "fri", "sat"])
test_series

sunday    2
mon       3
tue       4
wed       5
thur      6
fri       7
sat       8
dtype: int64

In [4]:
type(test_series)

pandas.core.series.Series

In [5]:
test_series.index

Index(['sunday', 'mon', 'tue', 'wed', 'thur', 'fri', 'sat'], dtype='object')

In [6]:
test_series.index.tolist()

['sunday', 'mon', 'tue', 'wed', 'thur', 'fri', 'sat']

### DataFrame

In [8]:
# Create a dataframe from a dictionary: having keys {'name':[], 'score':[]}
score = pd.DataFrame({"name":["Hari","Basanta","Gopi"],
              "score":[22,34,45]})

score

      name  score
0     Hari     22
1  Basanta     34
2     Gopi     45

In [9]:
type(score)

pandas.core.frame.DataFrame

In [11]:
score.index

RangeIndex(start=0, stop=3, step=1)

In [13]:
# create a dataframe from list of dictionaries

score = pd.DataFrame([{"name":"hari","score":22},
                      {"name":"basanta","score":34},
                      {"name":"gopi","score":45}])

score

      name  score
0     hari     22
1  basanta     34
2     gopi     45

## Loading csv and excel

In [21]:
df = pd.read_csv("class_scores.csv")
df.head()

,student_id,name,city,subject,marks,attendance_percent,exam_date
0,101,Aarav Sharma,Kathmandu,Python Programming,88,95.0,2026-05-02
1,102,Bibek Thapa,Pokhara,Statistics,72,88.5,2026-05-03
2,103,Chandni Rai,Biratnagar,Python Programming,45,70.0,2026-05-02
3,104,Deepika Gurung,Kathmandu,Machine Learning,91,98.0,2026-05-04
4,105,Esha KC,Lalitpur,Statistics,67,80.0,2026-05-03

In [22]:
df.tail()

,student_id,name,city,subject,marks,attendance_percent,exam_date
15,116,Prakash Yadav,Biratnagar,Machine Learning,77,89.0,2026-05-04
16,117,Queenie Rana,Pokhara,Python Programming,33,50.0,2026-05-02
17,118,Rohit Bista,Kathmandu,Statistics,85,92.0,2026-05-03
18,119,Sabina Ghale,Butwal,SQL,62,78.0,2026-05-05
19,120,Tenzin Sherpa,Lalitpur,Machine Learning,93,97.0,2026-05-04

In [23]:
df.shape

(20, 7)

### checking structure: info(), describe()

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   student_id          20 non-null     int64
 1   name                20 non-null     object
 2   city                20 non-null     object
 3   subject             20 non-null     object
 4   marks               20 non-null     int64
 5   attendance_percent  20 non-null     float64
 6   exam_date           20 non-null     object
dtypes: float64(1), int64(2), object(4)
memory usage: 1.2+ KB

In [25]:
df.describe()

       student_id      marks  attendance_percent
count    20.00000  20.000000           20.000000
mean    110.50000  69.150000           80.825000
std       5.91608  18.790465           14.886655
min     101.00000  33.000000           50.000000
25%     105.75000  57.250000           71.500000
50%     110.50000  70.000000           83.500000
75%     115.25000  85.750000           92.750000
max     120.00000  95.000000           99.000000

## Column selection

In [26]:
df["marks"]

0     88
1     72
2     45
3     91
4     67
5     58
6     39
7     82
8     95
9     61
10    74
11    48
12    90
13    55
14    68
15    77
16    33
17    85
18    62
19    93
Name: marks, dtype: int64

In [28]:
# multiple column
df_new = df[["marks","attendance_percent"]]

In [29]:
df_new

    marks  attendance_percent
0      88                95.0
1      72                88.5
2      45                70.0
3      91                98.0
4      67                80.0
5      58                65.0
6      39                55.0
7      82                90.0
8      95                99.0
9      61                72.0
10     74                85.0
11     48                60.0
12     90                96.0
13     55                75.0
14     68                82.0
15     77                89.0
16     33                50.0
17     85                92.0
18     62                78.0
19     93                97.0

## Selecting rows: loc and iloc

In [30]:
df.loc[2:5]

,student_id,name,city,subject,marks,attendance_percent,exam_date
2,103,Chandni Rai,Biratnagar,Python Programming,45,70.0,2026-05-02
3,104,Deepika Gurung,Kathmandu,Machine Learning,91,98.0,2026-05-04
4,105,Esha KC,Lalitpur,Statistics,67,80.0,2026-05-03
5,106,Faisal Khan,Butwal,Python Programming,58,65.0,2026-05-02

In [31]:
df.iloc[2:5]

,student_id,name,city,subject,marks,attendance_percent,exam_date
2,103,Chandni Rai,Biratnagar,Python Programming,45,70.0,2026-05-02
3,104,Deepika Gurung,Kathmandu,Machine Learning,91,98.0,2026-05-04
4,105,Esha KC,Lalitpur,Statistics,67,80.0,2026-05-03

### slicing rows and columns together

In [ ]:
# the end like [0,4] here 4 is inclusive in loc
df.loc[0:4,["name","subject","marks"]]

             name             subject  marks
0    Aarav Sharma  Python Programming     88
1     Bibek Thapa          Statistics     72
2     Chandni Rai  Python Programming     45
3  Deepika Gurung    Machine Learning     91
4         Esha KC          Statistics     67

In [ ]:
# 5 is exclusive in iloc
df.iloc[0:5,1:4]

             name        city             subject
0    Aarav Sharma   Kathmandu  Python Programming
1     Bibek Thapa     Pokhara          Statistics
2     Chandni Rai  Biratnagar  Python Programming
3  Deepika Gurung   Kathmandu    Machine Learning
4         Esha KC    Lalitpur          Statistics

In [35]:
# use .iloc() and select first 3 rows and columns: name,city
df.iloc[0:3,1:3]

           name        city
0  Aarav Sharma   Kathmandu
1   Bibek Thapa     Pokhara
2   Chandni Rai  Biratnagar

In [34]:
df

,student_id,name,city,subject,marks,attendance_percent,exam_date
0,101,Aarav Sharma,Kathmandu,Python Programming,88,95.0,2026-05-02
1,102,Bibek Thapa,Pokhara,Statistics,72,88.5,2026-05-03
2,103,Chandni Rai,Biratnagar,Python Programming,45,70.0,2026-05-02
3,104,Deepika Gurung,Kathmandu,Machine Learning,91,98.0,2026-05-04
4,105,Esha KC,Lalitpur,Statistics,67,80.0,2026-05-03
5,106,Faisal Khan,Butwal,Python Programming,58,65.0,2026-05-02
6,107,Gita Adhikari,Pokhara,Machine Learning,39,55.0,2026-05-04
7,108,Hari Bahadur,Kathmandu,SQL,82,90.0,2026-05-05
8,109,Isha Shrestha,Lalitpur,Statistics,95,99.0,2026-05-03
9,110,Jeevan Lama,Biratnagar,Python Programming,61,72.0,2026-05-02
10,111,Kabita Basnet,Kathmandu,SQL,74,85.0,2026-05-05
11,112,Lokesh Poudel,Pokhara,Machine Learning,48,60.0,2026-05-04
12,113,Maya Tamang,Butwal,Python Programming,90,96.0,2026-05-02
13,114,Nabin Karki,Kathmandu,Statistics,55,75.0,2026-05-03
14,115,Oshin Magar,Lalitpur,SQL,68,82.0,2026-05-05
15,116,Prakash Yadav,Biratnagar,Machine Learning,77,89.0,2026-05-04
16,117,Queenie Rana,Pokhara,Python Programming,33,50.0,2026-05-02
17,118,Rohit Bista,Kathmandu,Statistics,85,92.0,2026-05-03
18,119,Sabina Ghale,Butwal,SQL,62,78.0,2026-05-05
19,120,Tenzin Sherpa,Lalitpur,Machine Learning,93,97.0,2026-05-04

In [36]:
print(df.head(3).iloc[1:3])

   student_id         name        city             subject  marks  \
1         102  Bibek Thapa     Pokhara          Statistics     72
2         103  Chandni Rai  Biratnagar  Python Programming     45

   attendance_percent   exam_date
1                88.5  2026-05-03
2                70.0  2026-05-02

In [39]:
# implement using .loc method
df.loc[0:2,["name","city"]]

           name        city
0  Aarav Sharma   Kathmandu
1   Bibek Thapa     Pokhara
2   Chandni Rai  Biratnagar

In [40]:
df.loc[0:2, 'name':'city']

           name        city
0  Aarav Sharma   Kathmandu
1   Bibek Thapa     Pokhara
2   Chandni Rai  Biratnagar

## Boolean filtering

In [42]:
df["marks"] > 50

0      True
1      True
2     False
3      True
4      True
5      True
6     False
7      True
8      True
9      True
10     True
11    False
12     True
13     True
14     True
15     True
16    False
17     True
18     True
19     True
Name: marks, dtype: bool

In [43]:
df.head()

,student_id,name,city,subject,marks,attendance_percent,exam_date
0,101,Aarav Sharma,Kathmandu,Python Programming,88,95.0,2026-05-02
1,102,Bibek Thapa,Pokhara,Statistics,72,88.5,2026-05-03
2,103,Chandni Rai,Biratnagar,Python Programming,45,70.0,2026-05-02
3,104,Deepika Gurung,Kathmandu,Machine Learning,91,98.0,2026-05-04
4,105,Esha KC,Lalitpur,Statistics,67,80.0,2026-05-03

In [45]:
df[df["marks"]>50]

,student_id,name,city,subject,marks,attendance_percent,exam_date
0,101,Aarav Sharma,Kathmandu,Python Programming,88,95.0,2026-05-02
1,102,Bibek Thapa,Pokhara,Statistics,72,88.5,2026-05-03
3,104,Deepika Gurung,Kathmandu,Machine Learning,91,98.0,2026-05-04
4,105,Esha KC,Lalitpur,Statistics,67,80.0,2026-05-03
5,106,Faisal Khan,Butwal,Python Programming,58,65.0,2026-05-02
7,108,Hari Bahadur,Kathmandu,SQL,82,90.0,2026-05-05
8,109,Isha Shrestha,Lalitpur,Statistics,95,99.0,2026-05-03
9,110,Jeevan Lama,Biratnagar,Python Programming,61,72.0,2026-05-02
10,111,Kabita Basnet,Kathmandu,SQL,74,85.0,2026-05-05
12,113,Maya Tamang,Butwal,Python Programming,90,96.0,2026-05-02
13,114,Nabin Karki,Kathmandu,Statistics,55,75.0,2026-05-03
14,115,Oshin Magar,Lalitpur,SQL,68,82.0,2026-05-05
15,116,Prakash Yadav,Biratnagar,Machine Learning,77,89.0,2026-05-04
17,118,Rohit Bista,Kathmandu,Statistics,85,92.0,2026-05-03
18,119,Sabina Ghale,Butwal,SQL,62,78.0,2026-05-05
19,120,Tenzin Sherpa,Lalitpur,Machine Learning,93,97.0,2026-05-04

In [46]:
df[(df["marks"]>50) & (df["attendance_percent"] > 70)]

,student_id,name,city,subject,marks,attendance_percent,exam_date
0,101,Aarav Sharma,Kathmandu,Python Programming,88,95.0,2026-05-02
1,102,Bibek Thapa,Pokhara,Statistics,72,88.5,2026-05-03
3,104,Deepika Gurung,Kathmandu,Machine Learning,91,98.0,2026-05-04
4,105,Esha KC,Lalitpur,Statistics,67,80.0,2026-05-03
7,108,Hari Bahadur,Kathmandu,SQL,82,90.0,2026-05-05
8,109,Isha Shrestha,Lalitpur,Statistics,95,99.0,2026-05-03
9,110,Jeevan Lama,Biratnagar,Python Programming,61,72.0,2026-05-02
10,111,Kabita Basnet,Kathmandu,SQL,74,85.0,2026-05-05
12,113,Maya Tamang,Butwal,Python Programming,90,96.0,2026-05-02
13,114,Nabin Karki,Kathmandu,Statistics,55,75.0,2026-05-03
14,115,Oshin Magar,Lalitpur,SQL,68,82.0,2026-05-05
15,116,Prakash Yadav,Biratnagar,Machine Learning,77,89.0,2026-05-04
17,118,Rohit Bista,Kathmandu,Statistics,85,92.0,2026-05-03
18,119,Sabina Ghale,Butwal,SQL,62,78.0,2026-05-05
19,120,Tenzin Sherpa,Lalitpur,Machine Learning,93,97.0,2026-05-04

In [52]:
# filter students from kathmandu having subjects python programming or machine learning
df[(df["city"]=='Kathmandu') & ((df["subject"] == 'Python Programming') | (df["subject"] == 'Machine Learning'))]

,student_id,name,city,subject,marks,attendance_percent,exam_date
0,101,Aarav Sharma,Kathmandu,Python Programming,88,95.0,2026-05-02
3,104,Deepika Gurung,Kathmandu,Machine Learning,91,98.0,2026-05-04

## A more readable style: df.query()

In [57]:
df.query("city == 'Kathmandu' and (subject == 'Python Programming' or subject == 'Machine Learning')")

,student_id,name,city,subject,marks,attendance_percent,exam_date
0,101,Aarav Sharma,Kathmandu,Python Programming,88,95.0,2026-05-02
3,104,Deepika Gurung,Kathmandu,Machine Learning,91,98.0,2026-05-04

In [58]:
df.dtypes

student_id              int64
name                   object
city                   object
subject                object
marks                   int64
attendance_percent    float64
exam_date              object
dtype: object

In [59]:
df["passed"] = df["marks"] > 40

In [60]:
df

,student_id,name,city,subject,marks,attendance_percent,exam_date,passed
0,101,Aarav Sharma,Kathmandu,Python Programming,88,95.0,2026-05-02,True
1,102,Bibek Thapa,Pokhara,Statistics,72,88.5,2026-05-03,True
2,103,Chandni Rai,Biratnagar,Python Programming,45,70.0,2026-05-02,True
3,104,Deepika Gurung,Kathmandu,Machine Learning,91,98.0,2026-05-04,True
4,105,Esha KC,Lalitpur,Statistics,67,80.0,2026-05-03,True
5,106,Faisal Khan,Butwal,Python Programming,58,65.0,2026-05-02,True
6,107,Gita Adhikari,Pokhara,Machine Learning,39,55.0,2026-05-04,False
7,108,Hari Bahadur,Kathmandu,SQL,82,90.0,2026-05-05,True
8,109,Isha Shrestha,Lalitpur,Statistics,95,99.0,2026-05-03,True
9,110,Jeevan Lama,Biratnagar,Python Programming,61,72.0,2026-05-02,True
10,111,Kabita Basnet,Kathmandu,SQL,74,85.0,2026-05-05,True
11,112,Lokesh Poudel,Pokhara,Machine Learning,48,60.0,2026-05-04,True
12,113,Maya Tamang,Butwal,Python Programming,90,96.0,2026-05-02,True
13,114,Nabin Karki,Kathmandu,Statistics,55,75.0,2026-05-03,True
14,115,Oshin Magar,Lalitpur,SQL,68,82.0,2026-05-05,True
15,116,Prakash Yadav,Biratnagar,Machine Learning,77,89.0,2026-05-04,True
16,117,Queenie Rana,Pokhara,Python Programming,33,50.0,2026-05-02,False
17,118,Rohit Bista,Kathmandu,Statistics,85,92.0,2026-05-03,True
18,119,Sabina Ghale,Butwal,SQL,62,78.0,2026-05-05,True
19,120,Tenzin Sherpa,Lalitpur,Machine Learning,93,97.0,2026-05-04,True

## Cleanup

### Basic datatype conversion

In [61]:
df["marks"].dtype

dtype('int64')

In [63]:
df["marks"] = df["marks"].astype(float)

In [64]:
df["marks"].dtypes

dtype('float64')

### handling dates

In [65]:
df["exam_date"].dtypes

dtype('O')

In [66]:
df["exam_date"] = pd.to_datetime(df["exam_date"])

In [67]:
df["exam_date"].dtypes

dtype('<M8[ns]')

In [68]:
df["exam_date"].dt.day_name()

0     Saturday
1       Sunday
2     Saturday
3       Monday
4       Sunday
5     Saturday
6       Monday
7      Tuesday
8       Sunday
9     Saturday
10     Tuesday
11      Monday
12    Saturday
13      Sunday
14     Tuesday
15      Monday
16    Saturday
17      Sunday
18     Tuesday
19      Monday
Name: exam_date, dtype: object

In [71]:
df["exam_date"] > "2025-01-02"

0     True
1     True
2     True
3     True
4     True
5     True
6     True
7     True
8     True
9     True
10    True
11    True
12    True
13    True
14    True
15    True
16    True
17    True
18    True
19    True
Name: exam_date, dtype: bool

# day 4: Pandas Transformation and aggregation

In [3]:
import pandas as pd
import numpy as np

In [4]:
d= {
    'first_score': [100, 90, np.nan, 95],
    'Second_score': [30, 45, 56, np.nan],
    'Third_score': [np.nan, 40, 80, 98]
}
df= pd.DataFrame(d)
 
df.head()

   first_score  Second_score  Third_score
0        100.0          30.0          NaN
1         90.0          45.0         40.0
2          NaN          56.0         80.0
3         95.0           NaN         98.0

## checking missing values in pandas

In [5]:
df.isnull()

   first_score  Second_score  Third_score
0        False         False         True
1        False         False        False
2         True         False        False
3        False          True        False

In [6]:
df.isnull().sum()

first_score     1
Second_score    1
Third_score     1
dtype: int64

In [ ]:
bool_series = pd.isnull(df["first_score"])
df[bool_series]

   first_score  Second_score  Third_score
2          NaN          56.0         80.0

In [9]:
# na()
df.isna()

   first_score  Second_score  Third_score
0        False         False         True
1        False         False        False
2         True         False        False
3        False          True        False

In [10]:
# notnull()
df.notnull()

   first_score  Second_score  Third_score
0         True          True        False
1         True          True         True
2        False          True         True
3         True         False         True

In [11]:
nmv = pd.notnull(df["first_score"])
df[nmv]

   first_score  Second_score  Third_score
0        100.0          30.0          NaN
1         90.0          45.0         40.0
3         95.0           NaN         98.0

## Filling missing value

In [12]:
# fillna()
# 1. using zeros
df.fillna(0)

   first_score  Second_score  Third_score
0        100.0          30.0          0.0
1         90.0          45.0         40.0
2          0.0          56.0         80.0
3         95.0           0.0         98.0

In [13]:
df

   first_score  Second_score  Third_score
0        100.0          30.0          NaN
1         90.0          45.0         40.0
2          NaN          56.0         80.0
3         95.0           NaN         98.0

In [14]:
# forward value
df.ffill()

   first_score  Second_score  Third_score
0        100.0          30.0          NaN
1         90.0          45.0         40.0
2         90.0          56.0         80.0
3         95.0          56.0         98.0

In [15]:
# backword value
df.bfill()

   first_score  Second_score  Third_score
0        100.0          30.0         40.0
1         90.0          45.0         40.0
2         95.0          56.0         80.0
3         95.0           NaN         98.0

In [16]:
df["Second_score"].fillna(25)

0    30.0
1    45.0
2    56.0
3    25.0
Name: Second_score, dtype: float64

In [17]:
df

   first_score  Second_score  Third_score
0        100.0          30.0          NaN
1         90.0          45.0         40.0
2          NaN          56.0         80.0
3         95.0           NaN         98.0

In [18]:
# inplace = True
# for placing the value to original df

# or you can use the = operator
df['Second_score'] = df['Second_score'].fillna(25)

In [19]:
# using replace
data = df.replace(to_replace=np.nan, value=99.0)
data

   first_score  Second_score  Third_score
0        100.0          30.0         99.0
1         90.0          45.0         40.0
2         99.0          56.0         80.0
3         95.0          25.0         98.0

In [21]:
data = df["first_score"].replace(to_replace=np.nan, value=99.0)
data

0    100.0
1     90.0
2     99.0
3     95.0
Name: first_score, dtype: float64

## Dropping missing values

In [23]:
# for dropna() there should be atleast one nan value
df.dropna()

   first_score  Second_score  Third_score
1         90.0          45.0         40.0
3         95.0          25.0         98.0

In [24]:
d= {
    'first_score': [100, 90, np.nan, 95],
    'Second_score': [30, 45, 56, np.nan],
    'Third_score': [np.nan, 40, 80, 98]
}
df= pd.DataFrame(d)
 
df.head()

   first_score  Second_score  Third_score
0        100.0          30.0          NaN
1         90.0          45.0         40.0
2          NaN          56.0         80.0
3         95.0           NaN         98.0

In [25]:
df.dropna(axis = 1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

In [29]:
d= {
    'first_score': [np.nan, np.nan, np.nan, 95],
    'Second_score': [30, np.nan, 56, 25],
    'Third_score': [np.nan, np.nan, np.nan, 98]
}

data = pd.DataFrame(d)

data.dropna(axis = 1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

In [31]:
data

   first_score  Second_score  Third_score
0          NaN          30.0          NaN
1          NaN           NaN          NaN
2          NaN          56.0          NaN
3         95.0          25.0         98.0

In [30]:
data.dropna(how="all")

   first_score  Second_score  Third_score
0          NaN          30.0          NaN
2          NaN          56.0          NaN
3         95.0          25.0         98.0

## Duplicated values

In [32]:
df = pd.DataFrame(
    {
        "Name":['alice','bob','alice','charlie'],
        "Age":[25,32,25,37]
    }
)
df

      Name  Age
0    alice   25
1      bob   32
2    alice   25
3  charlie   37

In [34]:
df[df.duplicated()]

    Name  Age
2  alice   25

In [37]:
df.sort_values("Name",inplace=True)
df

      Name  Age
0    alice   25
2    alice   25
1      bob   32
3  charlie   37

In [38]:
bool_series = df["Name"].duplicated()

In [39]:
bool_series

0    False
2     True
1    False
3    False
Name: Name, dtype: bool

### removing the duplicated values

In [40]:
df[bool_series]

    Name  Age
2  alice   25

In [41]:
bool_series = df["Name"].duplicated(keep=False)
bool_series

0     True
2     True
1    False
3    False
Name: Name, dtype: bool

In [43]:
data = df[~bool_series]

In [44]:
bool_series = df["Name"].duplicated(keep='last')
bool_series
data = df[~bool_series]
data

      Name  Age
2    alice   25
1      bob   32
3  charlie   37

## Inconsistent text, numeric and data values

In [45]:
# lower()
df['Name'].str.lower()

0      alice
2      alice
1        bob
3    charlie
Name: Name, dtype: object

In [47]:
# upper
df['Name'].str.upper()

0      ALICE
2      ALICE
1        BOB
3    CHARLIE
Name: Name, dtype: object

In [49]:
# strip: remove spaces
df['Name'].str.strip()

0      alice
2      alice
1        bob
3    charlie
Name: Name, dtype: object

In [51]:
# seperate name into list in two parts using 'i' as seperator

df['Name'].str.split('i')

0      [al, ce]
2      [al, ce]
1         [bob]
3    [charl, e]
Name: Name, dtype: object

In [54]:
# length
df['Name'].str.len()

0    5
2    5
1    3
3    7
Name: Name, dtype: int64

In [55]:
# one hot encoding
df['Name'].str.get_dummies()

   alice  bob  charlie
0      1    0        0
2      1    0        0
1      0    1        0
3      0    0        1

In [56]:
# startswith()
# endswith()

In [57]:
# replace
df['Name'] = df['Name'].str.replace('bob','ram')

In [58]:
df

      Name  Age
0    alice   25
2    alice   25
1      ram   32
3  charlie   37

In [59]:
# swapcase

### numerical operation

In [65]:
df = pd.DataFrame(
    {
        "Price": [100,200,300],
        "Quantity":[2,3,4]
    }
)

In [66]:
# Basic arithmetic operation,
# + - * / ** % 
df["Price"] = df["Price"] + 10
df

   Price  Quantity
0    110         2
1    210         3
2    310         4

In [67]:
df["total"] = df["Price"] * df["Quantity"]
df

   Price  Quantity  total
0    110         2    220
1    210         3    630
2    310         4   1240

In [68]:
df["discounted_total"] = df["total"] * 0.9
df

   Price  Quantity  total  discounted_total
0    110         2    220             198.0
1    210         3    630             567.0
2    310         4   1240            1116.0

In [69]:
# Aggregation
# sum(), mean(), median(), max(), min(), std(), var()

df["total"].sum()

np.int64(2090)

In [ ]:
# min
df["Price"].min()

110

In [ ]:
# max
df["Price"].max()

310

In [72]:
# operation in entire dataframe
df.sum()

Price                630.0
Quantity               9.0
total               2090.0
discounted_total    1881.0
dtype: float64

In [73]:
# axis = 0 means row, 
# axis = 1 means columns

In [74]:
df.sum(axis=0)

Price                630.0
Quantity               9.0
total               2090.0
discounted_total    1881.0
dtype: float64

In [76]:
df.sum(axis = 1)

0     530.0
1    1410.0
2    2670.0
dtype: float64

In [77]:
df["Price"] > 120

0    False
1     True
2     True
Name: Price, dtype: bool

In [78]:
df[df["Price"] > 120]

   Price  Quantity  total  discounted_total
1    210         3    630             567.0
2    310         4   1240            1116.0

In [79]:
# < > == <=, >=, !=

In [80]:
df[(df["Price"] > 150) & (df["Quantity"] > 2)]

   Price  Quantity  total  discounted_total
1    210         3    630             567.0
2    310         4   1240            1116.0

In [81]:
#  &, |, ~

In [82]:
df["log_price"] = np.log(df["Price"])
df

   Price  Quantity  total  discounted_total  log_price
0    110         2    220             198.0   4.700480
1    210         3    630             567.0   5.347108
2    310         4   1240            1116.0   5.736572

In [83]:
# .round(2), floor()

df["log_price"].round(2)

0    4.70
1    5.35
2    5.74
Name: log_price, dtype: float64

In [85]:
# floor
np.floor(df["log_price"])

0    4.0
1    5.0
2    5.0
Name: log_price, dtype: float64

In [86]:
# ciel

In [87]:
df = pd.DataFrame(
    {
        "price": [100,200,None,400]
    }
)

In [88]:
df["price"].isna()

0    False
1    False
2     True
3    False
Name: price, dtype: bool

In [90]:
df["price"].fillna(df["price"].mean())

0    100.000000
1    200.000000
2    233.333333
3    400.000000
Name: price, dtype: float64

In [91]:
#  data time conversions
df = pd.DataFrame(
    {
        "date":[
            "2026-01-15",
            "2026-02-20",
            "2026-03-10"
        ]
    }
)

In [92]:
df["date"].dtype

dtype('O')

In [93]:
df["date"] = pd.to_datetime(df["date"])

In [94]:
df["date"].dtype

dtype('<M8[ns]')

In [96]:
df["date"] = pd.to_datetime(
    df["date"],
    format="%Y-%m-%d",
    errors = "coerce"
)
df["date"]

0   2026-01-15
1   2026-02-20
2   2026-03-10
Name: date, dtype: datetime64[ns]

In [100]:
# .dt.month, year, day, hour
df["year"] = df["date"].dt.year

In [101]:
df

        date  year
0 2026-01-15  2026
1 2026-02-20  2026
2 2026-03-10  2026

In [102]:
df["day"] = df["date"].dt.day_name()

In [103]:
df

        date  year       day
0 2026-01-15  2026  Thursday
1 2026-02-20  2026    Friday
2 2026-03-10  2026   Tuesday

In [104]:
df["week"] = df["date"].dt.weekday

In [105]:
df

        date  year       day  week
0 2026-01-15  2026  Thursday     3
1 2026-02-20  2026    Friday     4
2 2026-03-10  2026   Tuesday     1

In [106]:
# to string
df["date_string"] = df["date"].dt.strftime("%Y-%m-%d")
df

        date  year       day  week date_string
0 2026-01-15  2026  Thursday     3  2026-01-15
1 2026-02-20  2026    Friday     4  2026-02-20
2 2026-03-10  2026   Tuesday     1  2026-03-10

In [107]:
df[
    (df["date"] >= "2026-01-20")
]

        date  year      day  week date_string
1 2026-02-20  2026   Friday     4  2026-02-20
2 2026-03-10  2026  Tuesday     1  2026-03-10

## Aggregation data to summarize trends in pandas

In [108]:
df = pd.DataFrame(
    {
        "product":["A","A","B","B","C"],
        "sales":[100,150,200,250,300],
        "quantity":[2,3,4,5,6]
    }
)

In [109]:
df

  product  sales  quantity
0       A    100         2
1       A    150         3
2       B    200         4
3       B    250         5
4       C    300         6

In [110]:
df["sales"].sum()

np.int64(1000)

In [111]:
df.sum()

product     AABBC
sales        1000
quantity       20
dtype: object

In [113]:
df.describe()

            sales  quantity
count    5.000000  5.000000
mean   200.000000  4.000000
std     79.056942  1.581139
min    100.000000  2.000000
25%    150.000000  3.000000
50%    200.000000  4.000000
75%    250.000000  5.000000
max    300.000000  6.000000

In [114]:
# calculate sales for each product
# group by
df.groupby("product")["sales"].sum()

product
A    250
B    450
C    300
Name: sales, dtype: int64

In [115]:
# Multiple aggregations
df.groupby("product")["sales"].agg(
    [
        "sum",
        "mean",
        "min",
        "max"
    ]
)

         sum   mean  min  max
product
A        250  125.0  100  150
B        450  225.0  200  250
C        300  300.0  300  300

In [117]:
df.groupby("product").agg(
    {
        "sales":["sum","mean","min"],
        "quantity":["sum","mean","min"]
    }
)

        sales             quantity
          sum   mean  min      sum mean min
product
A         250  125.0  100        5  2.5   2
B         450  225.0  200        9  4.5   4
C         300  300.0  300        6  6.0   6

In [118]:
df.groupby("product").agg(
    total_sales = ("sales","sum"),
    average_sales = ("sales","mean"),
    total_quantity = ("quantity","sum"),
)

         total_sales  average_sales  total_quantity
product
A                250          125.0               5
B                450          225.0               9
C                300          300.0               6

In [120]:
df.groupby("product").count()

         sales  quantity
product
A            2         2
B            2         2
C            1         1

In [121]:
df.groupby("product").size()

product
A    2
B    2
C    1
dtype: int64

In [122]:
df.groupby("product")["sales"].count()

product
A    2
B    2
C    1
Name: sales, dtype: int64

In [124]:
df = pd.DataFrame(
    {
        "date":[
            "2026-01-15",
            "2026-01-15",
            "2026-02-20",
            "2026-02-20",
            "2026-03-10"
        ],
        "sales":[100,150,200,250,300]
    }
)

df["date"] = pd.to_datetime(df["date"])

In [125]:
df.groupby("date")["sales"].sum()

date
2026-01-15    250
2026-02-20    450
2026-03-10    300
Name: sales, dtype: int64

In [126]:
df["month"] = df["date"].dt.to_period("M")
df.groupby("month")["sales"].sum()

month
2026-01    250
2026-02    450
2026-03    300
Freq: M, Name: sales, dtype: int64

In [127]:
df = pd.DataFrame(
    {
        "region": ["East","East","West","West"],
        "product": ["A","B","A","B"],
        "sales": [100,200,150,300]
    }
)

df.groupby(["region","product"])["sales"].sum()

region  product
East    A          100
        B          200
West    A          150
        B          300
Name: sales, dtype: int64

In [128]:
pd.pivot_table(
    df,
    values = "sales",
    index = "region",
    columns = "product",
    aggfunc = "sum"
)

product    A    B
region
East     100  200
West     150  300

## Aggregation vs Transformation

In [129]:
df["sales_percentage"] = (
    df["sales"]/df["sales"].sum()
)

In [130]:
df

  region product  sales  sales_percentage
0   East       A    100          0.133333
1   East       B    200          0.266667
2   West       A    150          0.200000
3   West       B    300          0.400000

In [131]:
df.groupby("product")["sales"].mean()

product
A    125.0
B    250.0
Name: sales, dtype: float64

In [132]:
# groupby category and time in pandas

# df.groupby(["category","time"])["value"].agg(...)

Raw Data -> Transform -> Group/Aggregate -> Create Reprot -> Visualize

In [134]:
df = pd.DataFrame({ "date": [ "2026-01-01", "2026-01-05", "2026-01-10", "2026-02-01", "2026-02-10", "2026-02-15" ], "region": [ "East", "West", "East", "West", "East", "West" ], "product": [ "Laptop", "Laptop", "Phone", "Phone", "Laptop", "Phone" ], "quantity": [2, 1, 3, 4, 2, 5], "price": [1000, 1000, 500, 500, 1000, 500] })

In [135]:
df["date"] = pd.to_datetime(df["date"])
df["revenue"] = df["quantity"] * df["price"]

In [136]:
df

        date region product  quantity  price  revenue
0 2026-01-01   East  Laptop         2   1000     2000
1 2026-01-05   West  Laptop         1   1000     1000
2 2026-01-10   East   Phone         3    500     1500
3 2026-02-01   West   Phone         4    500     2000
4 2026-02-10   East  Laptop         2   1000     2000
5 2026-02-15   West   Phone         5    500     2500

In [137]:
report = {
    "total_revenue":df["revenue"].sum(),
    "total_quantity":df["quantity"].sum(),
    "total_transaction":len(df),
    "average_transaction":df["revenue"].mean()
}

In [138]:
report

{'total_revenue': np.int64(11000),
 'total_quantity': np.int64(17),
 'total_transaction': 6,
 'average_transaction': np.float64(1833.3333333333333)}

In [ ]:
report.to_csv(
    "sales_report.csv",
    index = False
)